spring:
  application:
    name: ach-poc-app

  datasource:


management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application